version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: mybooks-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd1234
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssw0rd1234
      MYSQL_DATABASE: mybooks_db
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql script
    networks:
      - mybooks-network

  web:
    build: .
    container_name: mybooks-web
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - mybooks-network

networks:
  mybooks-network:

volumes:
  db_data: